// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbCMx-0PMPipCtsHC5AkwmYD_zXdEAThU',
    appId: '1:622975986391:web:66afc73e1bd50adeef1e92',
    messagingSenderId: '622975986391',
    projectId: 'easy-bank-ad0bb',
    authDomain: 'easy-bank-ad0bb.firebaseapp.com',
    storageBucket: 'easy-bank-ad0bb.firebasestorage.app',
    measurementId: 'G-PKGHP43B0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtvjjxhrLeIcB7coj6zyaH2jwtoASsZA',
    appId: '1:622975986391:android:5ac125bc9022d7eeef1e92',
    messagingSenderId: '622975986391',
    projectId: 'easy-bank-ad0bb',
    storageBucket: 'easy-bank-ad0bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqOXPajSa0HD0gkmQdaUmplhJuMAQ3yIw',
    appId: '1:622975986391:ios:d9d3b3b66ee361f2ef1e92',
    messagingSenderId: '622975986391',
    projectId: 'easy-bank-ad0bb',
    storageBucket: 'easy-bank-ad0bb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqOXPajSa0HD0gkmQdaUmplhJuMAQ3yIw',
    appId: '1:622975986391:ios:d9d3b3b66ee361f2ef1e92',
    messagingSenderId: '622975986391',
    projectId: 'easy-bank-ad0bb',
    storageBucket: 'easy-bank-ad0bb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbCMx-0PMPipCtsHC5AkwmYD_zXdEAThU',
    appId: '1:622975986391:web:1837e07b02d841e9ef1e92',
    messagingSenderId: '622975986391',
    projectId: 'easy-bank-ad0bb',
    authDomain: 'easy-bank-ad0bb.firebaseapp.com',
    storageBucket: 'easy-bank-ad0bb.firebasestorage.app',
    measurementId: 'G-R4524GFSWF',
  );
}
